version: '3.8'

services:
  mongo-db:
    image: mongo:6.0
    container_name: assetflow-mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db

  web-backend:
    build: .
    container_name: assetflow-backend-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo-db:27017/assetflow_db
      - JWT_SECRET=your_docker_env_corporate_secret_jwt_signature_key
      - GOOGLE_CLIENT_ID=816937494129-qlo971fs0eavbk195e0fu3fkak01pfrh.apps.googleusercontent.com
    depends_on:
      - mongo-db

volumes:
  mongo-db-data:
